spring:
  application:
    name: benchmark
  profiles:
    active: online
server:
  port: 8002
  tomcat:
    max-connections: 2000
    threads:
      max: 800
      min-spare: 10
  servlet:
    context-path: /v1/smart-im
logging:
  config: classpath:logback-spring.xml
