spring:
  application:
    name: api
  profiles:
    active: online
    include: service
server:
  port: 8000
  tomcat:
    max-connections: 10000
    threads:
      max: 800
      min-spare: 10
    accept-count: 10000
  servlet:
    context-path: /v1/smart-im
logging:
  config: classpath:logback-spring.xml
config:
  tcp-loadbalance: roundrobin
