spring:
  application:
    name: web
  profiles:
    active: online
  thymeleaf:
    enabled: true
    encoding: utf-8
    prefix: classpath:/templates/
    cache: false
    mode: HTML
    suffix: .html
server:
  port: 8003
  tomcat:
    max-connections: 10000
    threads:
      max: 800
      min-spare: 100
    accept-count: 10000
  servlet:
    context-path: /v1/smart-im
logging:
  config: classpath:logback-spring.xml
