spring:
  application:
    name: tcpserver
  profiles:
    active: online
    include: service
server:
  port: 8001
  tomcat:
    max-connections: 2000
    threads:
      max: 800
      min-spare: 10
  servlet:
    context-path: /v1/smart-im
logging:
  config: classpath:logback-spring.xml
tcpserver:
  port: 7001
  boss-threads: 1
  worker-threads: 16
wsserver:
  port: 7002
  boss-threads: 1
  worker-threads: 16
udpserver:
  port: 7999
